### PR TITLE
Flow

### PR DESCRIPTION
**Pull request by tfarago**
# Visual programming for UFO
Users specify image processing algorithms as connected _boxes_, algorithm parameters are embedded directly in the boxes. Image processing results can be either stored or displayed directly in the GUI.

# Screenshot
tomo-axis

### CODE REVIEW

**Comment by tfarago** [comment]
needs #100

**Comment by matze** [comment]
Which `xdg` package is this? None that I know of exposes `HOME` as a name …

**Comment by tfarago** [comment]
https://pypi.org/project/xdg/
Please note that this is not `pyxdg` like in `concert`.

**Comment by matze** [comment]
I could've imagined you meant that but the latest version does not expose a `HOME` variable. Besides that I also had to comment out the `QLocale.setDefalt(QLocale.English)` and drop the `f=Qt.Window` parameter from the `PropertyLinks` constructor to make it work. But then it worked :+1:

**Comment by tfarago** [comment]
What do you use, PySide2? I wonder why you had to drop that stuff, maybe I should specify which backend one must have...

**Comment by matze** [comment]
> What do you use, PySide2?

Yes, looks like.

**Comment by tfarago** [comment]
Hmm, then it's weird. I will look into it.

**Comment by MarcusZuber** [comment]
> I could've imagined you meant that but the latest version does not expose a `HOME` variable. Besides that I also had to comment out the `QLocale.setDefalt(QLocale.English)` and drop the `f=Qt.Window` parameter from the `PropertyLinks` constructor to make it work. But then it worked +1

For me it was the same.
I should have read the PR before figuring it out on my own...

**Pull request merged**
