### PR TITLE
Find large spots median hysth

### PR DESCRIPTION
**Pull request by tfarago**
- unifies the behavior of spot and grow thresholds amongst "grow" and "median" method
- adds `--averaging-mode`
- adds `--max-spot-size`
- allows writing of the median-filtered image
- holes removal happens _after_ dilation

TODO:
 ~- [ ] do median calculations in UFO to speed things up~ later

### CODE REVIEW

**Comment by tfarago** [comment]
@sgasilov I put the sequence reader to util and updated all ez paths, please take a look, it should work.

**Comment by sgasilov** [comment]
Hello Tomas, 

Everything is working well now! One Q: - did you investigate that very slow convergence in my example if I set threshold to a low value like 1000? I left it the other day to run for 30 minutes and it was still computing. I wonder if I shall leave it running overnight just to see if it returns something at all? With 2000 and larger threshold all is well.

**Comment by tfarago** [comment]
Good to hear. It is slow because the time complexity is O(n^3), which is harsh for a python-based program, even with numpy backend. i will rewrite it on GPUs before merging.

**Comment by tfarago** [comment]
Merging as other updates are waiting

**Pull request merged**
