### PR TITLE
Many changes in tofu ez

### PR DESCRIPTION
**Pull request by sgasilov**
- fixed multiple bugs
- rewritten stitching tools
- inserted "todo"s

### CODE REVIEW

**Comment by tfarago** [comment]
The input directory is supposed to be a root dir with many data sets, right? I have such a root directory with one subdirectory to simulate the batch processing and when I select root as input it says 0 good data sets, when I specify the data set directory with darks, flats and radios it says 1 good data set. What am I missing here please?

root
└── dset
          ├── darks
          ├── flats
          ├── radios

**Comment by sgasilov** [comment]
Tomas, hello. These can happen for two reasons:
1) Did you change the "standard" name of your directory with projections to "radios" at the bottom of the main tab? By defaults it is called "tomo"
2) You last-level directories contain other files in addition to "tif". If there is "Thumb.db" file of any metadata in the directory with images it would disqualify it. So each directory with images must only contain one or more tif/bigtiff files with extension "tif". 

In regards to latter - has the python argparser been improved? Can we use the wildcard masks now? Years ago it was only possible to pass directory name to tofu commands unlike ufo-launch which can filter the content like tomo/*.tif.

**Comment by tfarago** [comment]
1. yes, it's radios and I renamed it accordingly
2. not that I know of (but I will double check tomorrow)

But the strange this is that when I selected the data set directory it told me it was valid. Is it supposed to work both ways? I mean single data set reco _and_ batch reco?

AFAIK you can use wildcards as long as they are not processed by bash, i.e. you need to pass them in quotes, e.g. `--projections "tomo/*.tif"`.

**Comment by sgasilov** [comment]
The fact that one data set is identified correctly when you point to it, but it would be found if you select an upper-level directory is very weird. I've just applied "dry-run" to a big directory with few TB of data and multiple data sets at different depth levels and it found and formatted commands for each one of them correctly 
image

hmmm....

**Comment by tfarago** [comment]
tofu_ez_0_good
What am I missing?

**Comment by tfarago** [comment]
Same thing if I remove the params.yaml.

**Comment by tfarago** [comment]
As suggested, I am merging so that people can start using this new version and we put off the investigation for later.

**Pull request merged**
