### PR TITLE
Fix #64 fix #75

### LINKED ISSUE #64: Fix reco.conf feature
Hi guys, 

as discussed with Tomas, I report the that reco.conf feature is very inconvenient right now. I do not mind than ufo stores last set of parameters that was used, I do not like that it tries to use them if the file exists in the directory. I suggest either to completely disable it or to add a flag/parameter in tofu script, which ignores reco.conf by default and only when active, will tell tofu to use parameters from the log file instead of those provided in the command line.

Thanks,
Sergei

### LINKED ISSUE #75: Just turn off reco.conf functionality please
Hi guys, 

reco.conf is still causing more troubles and brings virtually nothing good. I've started to face another problem with write permission whn I decided to completely separate raw data from reconstructed. I presume that there is no exception handling in this part of the code and if user wants to reconstruct data (or simply find axis of rotation) and launches tofu gui in the folder where he/she does not have write permissions then even Ctrl+C does not help. 

In addition to this the old problem with default flags has not been yet resolved. 

Please fix it in any way you find appropriate. This reco.conf  makes a lot of mess when you try to show how to use ufo to people who do not even have very good idea about difference in absolute and relative paths.

### PR DESCRIPTION
**Pull request by tfarago**
disable reco.conf unless --config is specified.

### CODE REVIEW

**Comment by tfarago** [comment]
@milkdrop can you check if it works as expected? Unless `--config` is specified, it shouldn't be read at all and the GUI doesn't save it automatically on exit.

**Comment by matze** [comment]
Hmm, I am not too fond of the last change. We should write if possible but outright disabling it is too much in my opinion. How would I recall those settings in the GUI now?

**Comment by tfarago** [comment]
Isn't there a `load` button? If not we can add it easily.

**Comment by milkdrop** [comment]
Hi Tomas,

It works well without --config, but something is wrong when the option is used:
(1) >tofu gui --config
.....
 File "build/bdist.linux-x86_64/egg/tofu/config.py", line 442, in parse_known_args
  File "build/bdist.linux-x86_64/egg/tofu/config.py", line 424, in get_config_name
IndexError: list index out of range

(2) >tofu gui --config lalal
no errors, but no file either after gui is closed

(3) then I also noticed that if you type only beginning of the argument
>tofu gui --con
then error is different
tofu gui: error: argument --config: expected one argument

My guess there is something wrong with operations on the strings on the line 424 in config.py but I do not have time to check now. 

Thanks for the prompt response by the way. 

Also to Matze about utility of config file. From my experience, there are not so many vital setting to recall in gui, really. paths can be specified in several seconds and axis can be found in, perhaps, another 10 seconds. Now the phase-retrieval parameters or I imagine Laminography settings (does gui provide input for lamino?) - these is a different story and sometimes I need to recall old parameters when I return to some work after a week. But IRL I have to keep tracking all manipulations on data in a separate file anyways, because parameters of crop, bin, remove outliers, blur, PR, ring removal are not saved anyways - and those are really important sometimes for the final result.

**Comment by matze** [comment]
> From my experience, there are not so many vital setting to recall in gui, really. paths can be specified in several seconds and axis can be found in, perhaps, another 10 seconds. Now the phase-retrieval parameters or I imagine Laminography settings (does gui provide input for lamino?) - these is a different story and sometimes I need to recall old parameters when I return to some work after a week.

I sure get your point, I just wanted to clarify that we still need some way to recall parameters.

> But IRL I have to keep tracking all manipulations on data in a separate file anyways, because parameters of crop, bin, remove outliers, blur, PR, ring removal are not saved anyways - and those are really important sometimes for the final result.

That is then a bug in my opinion. AFAIR the initial idea was to get identical reconstructions from both GUI and the auto-saved `reco.conf`. I think this stems from the fact that we do not have a good internal representation of "state". Instead, we conflate configuration with state …

**Comment by tfarago** [comment]
It's not just a flag, you need to specify a file name, e,g, like this:
`tofu gui --config reco.conf`
Does that fix it? I am not here next week, so I will get back to this the week after if it's not resolved yet :wink:

**Comment by milkdrop** [comment]
Hola, 

no, >tofu gui --config lalal does produce file after gui is closed. Does it work for you? If yes, I wonder what could be the reason

And have a very enjoyable week out of office )

**Comment by tfarago** [comment]
`tofu gui --config lalal` *starts* the gui with configuration loaded from `lalal` (convenience to file->open). If you want to save it you need to press file->save as (which fixes #75 ).
On the top of that, when `tofu` is invoked from command line it doesn't read the config file unless you specify it with the `--config` flag, so if you want to use the config file it's consistent across all the subcommands, including gui, i.e. `tofu [subcommand] --config lalal`. Is it OK like this?

**Comment by milkdrop** [comment]
Hi Tomas, 
now I understand the logic. It is perfectly fine by me!
Cheers,
Serg.

**Comment by tfarago** [comment]
If @matze agrees with the proposed changes I can check it once more thoroughly and we can merge. Your concern about the loading is not a big deal because there is "file->open" which loads the conf file.

**Comment by matze** [comment]
Yeah, go ahead :+1:

**Pull request merged**
