### PR TITLE
gui: support multitif in axis finding tab

### PR DESCRIPTION
**Pull request by tfarago**

### CODE REVIEW

**Comment by sgasilov** [comment]
Tomas, 
doesn't it load the entire tif into RAM? 
            first = tifffile.TiffFile(first_name).asarray().astype(np.float) ?
If true, isn't it better to use your reader from tofu util?  
first = read_image(first_name)[0].astype(np.float)
last = read_image(last_name)[-1].astype(np.float)
which doesn't appear to load all pages into RAM?

Cheers,
Sergei.

**Comment by tfarago** [comment]
> doesn't it load the entire tif into RAM?

Nope, it fetches one page from a tif file and reads that, I just tested it with tifffile version 2018.11.6

**Comment by tfarago** [comment]
As for the `read_image`, I will probably drop the 'memmap' because if one has file with greater size than the available RAM it fails spectacularly, same goes for concert. Actually, I will probably think of something which makes use of memmap if possible and a normal read if not. But one more thing I don't like is that with memmap the array is read-only, which is not aligned with the general reading policy, e.g. if you read and edf file you can change the array, which, in concert is often what one does.

**Comment by sgasilov** [comment]
Hi Tomas, 

tried line 462 in ipython again this time looking at top - it definitely loads all data into RAM
tifffile-multipage

In regards to read_image - this explains a lot. I was struggling to find a way to change data in place and failed. In the end I'm using deep copy and it results in memory leakage... Also if your optimize parameters script is called 200 times from tkinter to find axis of rotation by minimizing std and uses 100 steps each time computer can run out of RAM and I'm pretty sure that is because read_image is used in it.

**Comment by tfarago** [comment]
Are you sure you are looking at a fresh master branch? Because [this](https://github.com/ufo-kit/tofu/blob/master/tofu/gui.py#L462) is line 462, the executive code is on line 463 and it's not what you have in your screenshot.

**Comment by sgasilov** [comment]
Oh yes, you are right.

**Pull request merged**
