### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by tfarago**
I just wanted to fix `ufo-sinos`... But noticed that

* [x] overriding parameters from the config file doesn't work
* [x] config sections are not corresponding to what they actually represent
* [x] `ufo-flat-correct` generates the same parameters all over again
* [x] we can set up general reader (and other nodes) paramteres easily for _everybody_ to use (e.g. f3aa03ee912a5f765cb9e8030c3f4076505515da, c276715078b2c84414a592a04a4dc56c56fcad7d)
* [x] `ufo-estimate-center` doesn't work ([run](https://github.com/ufo-kit/tofu/blob/master/tofu/reco.py#L250) isn't defined nor imported) @matze could you please take a look at this?
* [x] We need to follow the naming from [ufo-filters#61](https://github.com/ufo-kit/ufo-filters/pull/61) (tested with `ufo-flat-correct`, `ufo-reconstruct` (only fbp), `ufo-perf` and `ufo-sinos`)
* [x] `ufo-reconstruct` loads in GUI stuff all the time which is unfortunate if one doesn't have the GUI packages installed but could use the CLI
* [x] `from_projections` and other `store_true` params don't work
* [x] config template is incomplete (probably better to get rid of it completely and use the sections with their defaults)
* [x] we use underscores instead of dashes
* [x] laminography doesn't work
* [x] laminography doesn't support flat correction
* [x] GUI doesn't support absorptivity
* [x] `crop-width` should be removed from GUI
* [x] Unify scattered image readers and use them instead if `width` and `height` options are not specified
* [x] Support correlation-based estimation of the axis
* ~~[ ] `ufo-estimate-center` leaks memory and eventually segfaults~~

~~@MariaMatveeva could you please remove the `crop-width` option and add `absorptivity` option for the flat correction? The new padding will work "out-of-the-box" because you compute the width and height of input.~~

Example for reconstructing a certain subset of projections (case of more tomograms in a data set) and a subset of sinograms with flat correction:
`ufo-reconstruct tomo --input "radios/*.tif" --output slices/slice-%04i.tif --start 250 --end 750 --y 100 --height 10 --darks "darks/*" --flats "flats/*" --from_projections --axis 669 --width 1392 --absorptivity`

### CODE REVIEW

**Comment by matze** [comment]
About the centering script, do we still need that considering that the GUI provides a more precise feedback?

**Comment by tfarago** [comment]
It uses different algorithm, so I guess we should keep both. Actually we should integrate this one to the GUI.

**Comment by matze** [comment]
Alright, let me check it then.

**Comment by matze** [comment]
Hmm, concerning the estimate thing, there are actually three approaches:

1. The standalone script using the filter that does the computation using the mirroring.
2. The function based on the Donath method that's currently not working.
3. Maria's work based on convolution.

My suggestion is to remove the standalone script and fix the Donath method.

**Comment by matze** [comment]
@tfarago: I pushed two commits (just in case you try to fail to push).

**Comment by tfarago** [comment]
Damn, I pushed with -f to fix something, could you push again? And from now on no forcing (only in the end).

**Comment by tfarago** [comment]
Regarding the center estimation you are right.

**Comment by matze** [comment]
@tfarago: is the KIT network down? I cannot reach mail, VPN or www.kit.edu.

**Comment by tfarago** [comment]
I was also struggling for a while but then it got better.

**Comment by tfarago** [comment]
@matze could you please fix [lamino](https://github.com/ufo-kit/tofu/blob/master/tofu/reco.py#L169), there is some stale code. Once that works we can *finally* start thinking of merging this monster.

**Comment by matze** [comment]
Doesn't make it easier with the broken lamino config code :weary:

**Comment by tfarago** [comment]
Vicious circle :smile: I will have a look and prefix the config code so you can do your thing.

**Comment by matze** [comment]
No no, I am onto it.

**Comment by matze** [comment]
Hope, I didn't break anything now …

**Comment by tfarago** [comment]
I am checking it.

**Comment by matze** [comment]
If you are waiting for my go … go :+1:

**Comment by tfarago** [comment]
I am fixing the `required` thing which is hopefully the last. Then I'll clean up and remind you but hopefully no more "big" changes.

**Comment by tfarago** [comment]
I squashed because it was unbearable.

**Comment by tfarago** [comment]
@matze When I try the estimation I get:
```bash
ufo-reconstruct estimate --input sinos/ --output slices/slice-%04i.tif --num-iterations 5

(process:30640): ocl-CRITICAL **: Error </home/farago/dev/ufo-core/ufo/ufo-profiler.c:145>: CL_MEM_OBJECT_ALLOCATION_FAILURE

(process:30640): ocl-CRITICAL **: Error </home/farago/dev/ufo-core/ufo/ufo-profiler.c:145>: CL_MEM_OBJECT_ALLOCATION_FAILURE

(process:30640): ocl-CRITICAL **: Error </home/farago/dev/ufo-filters/src/ufo-ifft-task.c:278>: CL_MEM_OBJECT_ALLOCATION_FAILURE

(process:30640): ocl-CRITICAL **: Error </home/farago/dev/ufo-core/ufo/ufo-buffer.c:474>: CL_MEM_OBJECT_ALLOCATION_FAILURE

(process:30640): ocl-CRITICAL **: Error </home/farago/dev/ufo-core/ufo/ufo-buffer.c:475>: CL_INVALID_EVENT

(process:30640): ocl-CRITICAL **: Error </home/farago/dev/ufo-core/ufo/ufo-buffer.c:476>: CL_INVALID_EVENT

(process:30640): ocl-CRITICAL **: Error </home/farago/dev/ufo-core/ufo/ufo-profiler.c:145>: CL_MEM_OBJECT_ALLOCATION_FAILURE

(process:30640): ocl-CRITICAL **: Error </home/farago/dev/ufo-core/ufo/ufo-buffer.c:453>: CL_MEM_OBJECT_ALLOCATION_FAILURE
Segmentation fault
```

for sinograms of shape 1392x500 and a machine with 1GB video memory. Is suppose this is the same memory leak problem mentioned on other places of `ufo-kit` already.
I suppose there is nothing you can do about it within this PR so let's just skip it and finish this with the remaining TODOs wihch I'll do today.

**Comment by tfarago** [comment]
If @matze agrees that the last TODO point will be fixed elsewhere this is ready to be reviewed. If nothing else is needed I will clean up all the pep8 garbage and merge it.

**Comment by matze** [comment]
> If @matze agrees that the last TODO point will be fixed elsewhere this is ready to be reviewed.

He does agree. Good, tedious work :+1:

**Pull request merged**
