### PR TITLE
New lamino

### PR DESCRIPTION
**Pull request by tfarago**
This is a prototype which requires some programming on ufo-core to be done.
Prerequisite: [ufo-core#102](https://github.com/ufo-kit/ufo-core/pull/102)

### CODE REVIEW

**Comment by tfarago** [comment]
Since the lamino filter is coming soon I guess this is in order. However, there are some nasty workarounds in the code, see the TODOs.

**Comment by matze** [comment]
Reads like a novel :-)

Despite the workarounds this looks good to me :+1:

**Comment by tfarago** [comment]
Actually, I will do it and I can test it right away, just a second.

**Comment by tfarago** [comment]
I squashed everything because who cares about all the intermediate API updates. If @matze agrees he can merge.

**Pull request merged**
