### PR TITLE
GUI cleanup

### PR DESCRIPTION
**Pull request by matze**
This PR is exclusively related to the GUI and fixes some minor annoyances with the code and the GUI itself. Once merged, I think we can present it to the users.

- [x] Allow detaching views

### CODE REVIEW

**Comment by matze** [comment]
@tfarago I am nearing completion, so if you could have a look at the current state of both the GUI and the functionality. Here's a screenshot of this upon which we can base further discussions:

tofui

**Comment by tfarago** [comment]
It looks good, I like the restructuring of `show`*. I also wouldn't worry about the `browse` buttons... I found this:

* #28 is still there when I have `uint16` data.
* Center of rotation axis displayed by the GUI is wrong, I have a data set where I know the axis is 669, I overlap the images and when they "look good" GUI says 751. Funnily, the correlation works and gives correct result but the images which it overlaps and shifts are wrong. I guess it is just wrong `np.roll` call or something like this.
* Exceptions are not translated to the usual GUI "error" boxes, but what is worse the whole GUI still freezes when they occur.
* I get an exception when I want to reconstruct from sinograms:
```
python
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/tofu/gui.py", line 433, in on_reconstruct
  File "build/bdist.linux-x86_64/egg/tofu/gui.py", line 53, in _get_filtered_filenames
OSError: [Errno 2] No such file or directory: ''
```

**Comment by matze** [comment]
> Exceptions are not translated to the usual GUI "error" boxes, but what is worse the whole GUI still freezes when they occur.

We have to fix that on a case-by-case basis, because there are too many places where things could fail. Detecting such things isn't made easy the way the program is currently structured.

I will care about the remaining issues.

**Comment by matze** [comment]
> I get an exception when I want to reconstruct from sinograms:

What input path did you use? I just checked and for me it worked.

**Comment by tfarago** [comment]
When you keep the "Do flat-field  correction" checked and you are reconstructing from sinograms and the "Dakrs" and "Flat" fields are empty. You can manage by clicking to "Projections", check the "flat..." and then switch back to "sinograms". That way the check box is greyed out but still checked.

**Comment by tfarago** [comment]
Oh and please don't call it "absorption correction". Let's stick with `absorptivity` as in `tofu` or alternate [Absorbance](http://en.wikipedia.org/wiki/Absorbance).

**Comment by matze** [comment]
The problem with just "absorptivity" is that it does not make much sense for a GUI element that signifies an option (i.e. a state that can be on or off). If you come up with a name that denotes an action I will change that.

**Comment by tfarago** [comment]
"Use absorptivity"

**Comment by matze** [comment]
I should've addressed all issues you mentioned.

**Comment by matze** [comment]
@tfarago: I squashed everything. I'd start refactoring the visualization once this PR lands to not clutter this any more than necessary.

**Comment by tfarago** [comment]
I will review this ASAP, don't merge yet please.

**Comment by tfarago** [comment]
The subtraction of `uint16` is OK now. However:
* The axis calculation is still wrong (I see perfect overlap but the GUI tells me it's somewhere else)
* When I close the *Show slices* subwindow I can't get it back (same for *Show volume*)

**Comment by matze** [comment]
> The axis calculation is still wrong (I see perfect overlap but the GUI tells me it's somewhere else).

A precise example would be a lot more helpful. I have a dataset for which the calculation is roughly good and the computed axis gives a pretty good result, so for me the display of the axis works. Further fine tuning is only possible by reconstruction.

**Comment by tfarago** [comment]
I emailed you a verbose example.

**Comment by tfarago** [comment]
Works. Let's postpone thorough review once the merging of visualization is done. :+1:

**Pull request merged**
