### PR TITLE
Added support for ufo-remote-nodes

### PR DESCRIPTION
**Pull request by TimoDritschler**
First draft. Works so far.
Suggestions?

### CODE REVIEW

**Comment by TimoDritschler** [comment]
I refactored the ```sched.run()``` part into its own function.
Also, the arg parser now expects all remotes as one list of strings.
@tfarago could you maybe do a quick test to see if laminography is still working as intended? I don't have any lamino setup and/or data available to test it myself.

**Comment by tfarago** [comment]
Thanks for the heads up. The lamino code is being refactored, so don't worry about it for now, I will keep this in mind when I make it a PR (which won't be so soon).

**Comment by matze** [comment]
After squashing, I'll merge :+1:

**Comment by TimoDritschler** [comment]
Done

**Pull request merged**
