### PR TITLE
Refactor visualization

### PR DESCRIPTION
**Pull request by matze**
As sketched in [this PR](https://github.com/ufo-kit/concert/pull/258) the following changes modularize the code by moving visualization and GUI logic into separate widgets.

By changing the transfer function of the volume viewer to a gradient-based method we can probably live with the fact that I removed some contrast-enhancing mechanisms available in previous version. As a matter of fact, I think the current iteration 

tofu3d

is more meaning- and useful than the previous one

tofui

### CODE REVIEW

**Comment by matze** [comment]
@pavel-rybalko I guess you can start now using tofu as a (soft) dependency and sooner or later add you meshing code as well.

**Comment by tfarago** [comment]
Obviously I like the 3D version you have now, nice. We should end this up before end of March so Pavel's GUI is in its "final" state as well.

**Comment by matze** [comment]
I don't know if @pavel-rybalko can commit, so I'd suggest to merge this as soon as there are no blatant problems with it and let him open a new PR to add his mesh code.

**Comment by tfarago** [comment]
Is it ready? Should I play with it already?

**Comment by matze** [comment]
Yeah, definitely. The main task of this PR is ripping out the GUI elements and provide them as custom widgets.

**Comment by tfarago** [comment]
:+1: go ahead

**Pull request merged**
